config/routes.rb
Rails.application.routes.draw do
  resources :people do
    resources :phones
  end
  get 'welcome/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :phones

  validates :name, presence: true, uniqueness: true, length: { minimum: 5, maximum: 255 }
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :person

  validates :number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :birth_date, :email)
    end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
  def create
    @person = Person.find(params[:person_id])
    @phone	= @person.phones.create(phone_params)

    redirect_to person_path(@person)
  end

  def destroy
    @person = Person.find(params[:person_id])
    @phone  = @person.phones.find(params[:id])
    @phone.destroy

    redirect_to person_path(@person)
  end

  private
    def phone_params
      params.require(:phone).permit(:number)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = params[:name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
  def date_to_br(date)
    return if date.nil?

    date.strftime('%d/%m/%Y')
  end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :person_name %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date, id: :person_birth_date %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :person_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth date</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= date_to_br(person.birth_date) %></td>
        <td><%= person.email %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= date_to_br(@person.birth_date) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<h2>Phones</h2>

<ul>
  <% @person.phones.each do |phone| %>
    <li>
      <%= link_to '[x]',  person_phone_path(@person, phone), data: { confirm: 'Are you sure?' }, method: :delete %>
      <%= phone.number %>
    </li>
  <% end %>
</ul>

<a href="#" onclick="toggleForm()">
  [+] Add phone
</a>

<fieldset id="phone_form" style="display: none">
  <legend>Add new phone</legend>

  <%= form_for([@person, @person.phones.build]) do |f| %>
    <div class="field">
      <%= f.label :number %>
      <%= f.text_field :number %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</fieldset>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

<script type="text/javascript">
  function toggleForm(){
    obj = document.getElementById('phone_form');
    if(obj.style.display == 'none'){
      obj.style.display = 'block';
    } else {
      obj.style.display = 'none';
    }
  }
</script>

app/views/welcome/index.html.erb
<h1>Hello, Rails</h1>

<% if @name -%>
  <h2>Bem vindo, <%= @name %></h2>
<% end %>